name: Workflow Commands Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - id: hello
        run: |
            ./workflow-commands-demo/demo.sh

